# Build website
[build]
  command = "yarn run docs:build:prod"
  publish = "./docs/dist/"

# Terry Pratchett homage
[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
