#!/usr/bin/env sh


testPath="./tmp/test-manual";
inputPath="$testPath/input.css"
outputPath="$testPath/output.css"
configPath="modules/tailwind-config-norska/lib/main.js"

mkdir -p $testPath
rm -f $testPath/style.css
echo "@tailwind base;" > $inputPath
echo "@tailwind components;" > $inputPath
echo "@tailwind utilities;" > $inputPath

yarn run tailwindcss build \
  "$inputPath" \
  --config "$configPath" \
  --output "$outputPath"

