#!/usr/bin/env sh
set -e

rootPath=$PWD;
testPath="$rootPath/tmp/test-manual";
inputPath="$testPath/input.css"
outputPath="$testPath/output.css"

modulePath="$rootPath/modules/lib"
binPath="$modulePath/node_modules/.bin/tailwindcss"
configPath="$modulePath/lib/main.js"

mkdir -p "$testPath"
rm -f "$testPath/style.css"
{
  echo "@tailwind base;"
  echo "@tailwind components;"
  echo "@tailwind utilities;"
} > "$inputPath"

$binPath build \
  "$inputPath" \
  --config "$configPath" \
  --output "$outputPath"

