#!/usr/bin/env sh
set -e

mkdir -p ./tmp/test
rm -f ./tmp/test/style.css
{ 
  echo '@tailwind base;'
  echo '@tailwind components;'
  echo '@tailwind utilities;'
} >> ./tmp/test/style.css

tailwindcss build \
  ./tmp/test/style.css \
  --config ./lib/main.js \
  --output ./tmp/test/output.css
